### ISSUE TITLE
relbo calculation

### ISSUE THREAD

**Issue by TNU-yaoy** [ratschlab/projects2019-boosting-bbvi-pyro#12]
https://github.com/ratschlab/projects2019-boosting-bbvi-pyro/blob/8bc117176e96fc31ce043b3f70e62ba3b5dc816e/bbbvi.py#L41

I think the elbo calculated here is being overwritten later

**Comment by lorenzkuhn** [comment]
Yeah, you're right. I'm aware of this and this is a result of me testing different ways of computing the ELBO - will remove one of the formulations when refactoring. Thanks!
