### ISSUE TITLE
try more than two iterations for toy squared-mu model

### ISSUE THREAD

**Issue by gideonite** [ratschlab/projects2019-boosting-bbvi-pyro#4]

**Comment by lorenzkuhn** [comment]
Just ran a quick test of BBBVI for our bimodal posterior toy problem with six approximation components. I used the hyperparameters that gave us the best approximation for two approximation components. The true modes of the posterior are around -2 and + 2.

The approximation with two components:
![approximation](https://user-images.githubusercontent.com/9898136/69005241-7c2a3b00-091f-11ea-8918-229650d757aa.png)


The approximation with six components:
![six_component_approximation](https://user-images.githubusercontent.com/9898136/69005234-52711400-091f-11ea-9509-34bbd6781c0c.png)
