### ISSUE TITLE
Get ChemReact i.e. try a larger dataset.

### ISSUE THREAD

**Issue by gideonite** [ratschlab/projects2019-boosting-bbvi-pyro#8]

**Comment by gideonite** [comment]
It's available on the cluster `/cluster/work/grlab/projects/boosting-bbvi/data/chem`. Let me know if you have permissions issues. Send me your username. @lorenzkuhn

**Comment by lorenzkuhn** [comment]
Is this on the Euler or the Leonhard cluster? I can't seem to find `/cluster/work/grlab` on either of them. My nethz username is @kuhnl. Thanks!

**Comment by gideonite** [comment]
It's on leonard. I can access it from `lm-login-01`.

**Comment by lorenzkuhn** [comment]
Hmm, maybe I'm doing something wrong:

- `ssh kuhnl@login.leonhard.ethz.ch`
-  `cd /cluster/work/grlab` which gets me a `cd: /cluster/work/grlab: No such file or directory`

Do you have an idea what I might be doing wrong, @gideonite ?
