### ISSUE TITLE
Weighting of RELBO terms

### ISSUE THREAD

**Issue by sharrison5** [ratschlab/projects2019-boosting-bbvi-pyro#9]
Had a chance to go through `bimodal_posterior.py` (made a few tweaks on `wip/sam-tests`). The thing that surprised me was how strong the contribution of `approximation_trace.log_prob_sum()` is. For example, for the second component this seems to completely dominate, and rather than settling on the other true mode, the posterior is pushed much further away from the first component to a region of parameter space that is a poor fit to the data. In other words, it seems like the optimisation is minimising the RELBO primarily by making the `q_t` terms as different as possible.

I don't think this is a bug, but the behaviour is surprising (to me at least). Thought I'd share in case anyone else has any thoughts on this?

**Comment by lorenzkuhn** [comment]
Nice, thanks @sharrison5. 

Yeah, I observed the same when I plotted the components of the RELBO. Do you remember seeing this with your Edward implementation as well, @gideonite? 

I've plotted the different terms of the RELBO throughout SVI for the second component of the approximation. I also found that in the cases where the magnitude of `approximation_trace.log_prob_sum()` was closer to the magnitude of `model_trace.log_prob_sum()`, we'd get an approximation which was closer to the true modes. This ratio between `approximation_trace.log_prob_sum()` and `model_trace.log_prob_sum()` varied a lot for different initialisations and hyperparameter choices.

If the plot of the RELBO components looks like this, for instance: 
![relbo_components_2](https://user-images.githubusercontent.com/9898136/69005308-b1835880-0920-11ea-8526-3be9118736c5.png)
the new component would be pushed away from the true mode.

But if it looks more like this:
![relbo_components_2](https://user-images.githubusercontent.com/9898136/69005318-d1b31780-0920-11ea-977d-1d80a2b3f759.png)

the new component end up being very close to the true mode, as we'd expect.

**Comment by sharrison5** [comment]
Perfect, thanks @lorenzkuhn! Yes, the issue seems to be that it's as beneficial to be as far away from the current approximation as to fit the data (and this seems to hold even if you use 10x as much data).
